# Runtime configuration of second BIG-IP HA instance w/embedded license key
# yamllint disable rule:line-length
---
controls:
  logLevel: info
  logFilename: /var/log/cloud/bigIpRuntimeInit.log
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.31.0
      extensionHash: 8c31d858f78100ce866b70fdf73ebc47f05adbdd2e62ac6ecc4a2162645fc852
    - extensionType: as3
      extensionVersion: 3.38.0
      extensionHash: 38b9b96826c2da997750ba2054811d8606768df43d08b870d68f8d7cb3fff58d
    - extensionType: cf
      extensionVersion: 1.11.0
      extensionHash: f3c7aca8a19d0dc01e529d38aa0d235b4dfad34beec2584f8402aa9a92c34699
extension_services:
  service_operations:
    - extensionType: do
      type: inline
      value:
        schemaVersion: 1.0.0
        class: Device
        async: true
        label: FAILOVER 2NIC BIG-IP declaration for Declarative Onboarding with BYOL
          license
        Common:
          class: Tenant
          My_DbVariables:
            class: DbVariables
            provision.extramb: 1000
            restjavad.useextramb: true
            config.allow.rfc3927: enable
            dhclient.mgmt: disable
            tm.tcpudptxchecksum: Software-only
          My_Provisioning:
            class: Provision
            ltm: nominal
          My_Ntp:
            class: NTP
            servers:
              - 169.254.169.254
            timezone: UTC
          My_Dns:
            class: DNS
            nameServers:
              - 169.254.169.254
            search:
              - f5.com
          My_System:
            autoPhonehome: true
            class: System
            hostname: '{{{NAME}}}.example'
          My_License:
            class: License
            licenseType: regKey
            regKey: WHETJ-ZPSCB-JIGXL-JIELW-KVHNLOW
          admin:
            class: User
            userType: regular
            password: '{{{BIGIP_PASSWORD}}}'
            shell: bash
          externalGwRoute:
            class: Route
            target: external
            network: '{{{EXTERNAL_GW}}}/32'
            mtu: 1460
          externalIntRoute:
            class: Route
            gw: '{{{EXTERNAL_GW}}}'
            network: '{{{EXTERNAL_NETWORK}}}/{{{EXTERNAL_BITMASK}}}'
            mtu: 1460
          default:
            class: Route
            gw: '{{{EXTERNAL_GW}}}'
            network: default
            mtu: 1460
          external:
            class: VLAN
            tag: 4094
            mtu: 1460
            interfaces:
              - name: '1.0'
                tagged: false
          external-self:
            class: SelfIp
            address: '{{{SELF_IP_EXTERNAL}}}/32'
            vlan: external
            allowService:
              - tcp:80
              - tcp:443
              - tcp:4353
              - udp:1026
            trafficGroup: traffic-group-local-only
    - extensionType: cf
      type: inline
      value:
        schemaVersion: 1.0.0
        class: Cloud_Failover
        environment: gcp
        controls:
          class: Controls
          logLevel: silly
        externalStorage:
          scopingTags:
            f5_cloud_failover_label: bigip_high_availability_solution
        failoverAddresses:
          enabled: true
          scopingTags:
            f5_cloud_failover_label: bigip_high_availability_solution
          requireScopingTags: false
    - extensionType: do
      type: inline
      value:
        schemaVersion: 1.0.0
        class: Device
        async: true
        label: FAILOVER 2NIC BIG-IP declaration for Declarative Onboarding with BYOL
          license
        Common:
          class: Tenant
          My_DbVariables:
            class: DbVariables
            provision.extramb: 1000
            restjavad.useextramb: true
            config.allow.rfc3927: enable
            dhclient.mgmt: disable
            tm.tcpudptxchecksum: Software-only
          My_Provisioning:
            class: Provision
            ltm: nominal
          My_Ntp:
            class: NTP
            servers:
              - 169.254.169.254
            timezone: UTC
          My_Dns:
            class: DNS
            nameServers:
              - 169.254.169.254
            search:
              - f5.com
          My_System:
            autoPhonehome: true
            class: System
            hostname: '{{{NAME}}}.example'
          admin:
            class: User
            userType: regular
            password: '{{{BIGIP_PASSWORD}}}'
            shell: bash
          externalGwRoute:
            class: Route
            target: external
            network: '{{{EXTERNAL_GW}}}/32'
            mtu: 1460
          externalIntRoute:
            class: Route
            gw: '{{{EXTERNAL_GW}}}'
            network: '{{{EXTERNAL_NETWORK}}}/{{{EXTERNAL_BITMASK}}}'
            mtu: 1460
          default:
            class: Route
            gw: '{{{EXTERNAL_GW}}}'
            network: default
            mtu: 1460
          external:
            class: VLAN
            tag: 4094
            mtu: 1460
            interfaces:
              - name: '1.0'
                tagged: false
          external-self:
            class: SelfIp
            address: '{{{SELF_IP_EXTERNAL}}}/32'
            vlan: external
            allowService:
              - tcp:80
              - tcp:443
              - tcp:4353
              - udp:1026
            trafficGroup: traffic-group-local-only
          configSync:
            class: ConfigSync
            configsyncIp: '{{{SELF_IP_EXTERNAL}}}'
          failoverAddress:
            class: FailoverUnicast
            address: '{{{SELF_IP_EXTERNAL}}}'
          failoverGroup:
            class: DeviceGroup
            type: sync-failover
            members:
              - 172.16.0.11
              - 172.16.0.12
            owner: /Common/failoverGroup/members/0
            autoSync: true
            saveOnAutoSync: false
            networkFailover: true
            fullLoadOnSync: false
            asmSync: false
          trust:
            class: DeviceTrust
            localUsername: admin
            localPassword: '{{{BIGIP_PASSWORD}}}'
            remoteHost: /Common/failoverGroup/members/0
            remoteUsername: admin
            remotePassword: '{{{BIGIP_PASSWORD}}}'
pre_onboard_enabled: []
runtime_parameters:
  - name: BIGIP_PASSWORD
    type: secret
    secretProvider:
      environment: gcp
      type: SecretsManager
      version: latest
      secretId: emes-gdm-bigip-password
  - name: NAME
    type: url
    value: http://169.254.169.254/computeMetadata/v1/instance/name
    headers:
      - name: Metadata-Flavor
        value: Google
  - name: PROJECT_ID
    type: url
    value: http://169.254.169.254/computeMetadata/v1/project/project-id
    headers:
      - name: Metadata-Flavor
        value: Google
  - name: UNIQUE
    type: url
    value: http://169.254.169.254/computeMetadata/v1/instance/attributes/unique-string
    headers:
      - name: Metadata-Flavor
        value: Google
  - name: SELF_IP_EXTERNAL
    type: metadata
    metadataProvider:
      environment: gcp
      type: network
      field: ip
      index: 0
      ipcalc: address
  - name: EXTERNAL_GW
    type: metadata
    metadataProvider:
      environment: gcp
      type: network
      field: ip
      index: 0
      ipcalc: first
  - name: EXTERNAL_BITMASK
    type: metadata
    metadataProvider:
      environment: gcp
      type: network
      field: ip
      index: 0
      ipcalc: bitmask
  - name: EXTERNAL_NETWORK
    type: metadata
    metadataProvider:
      environment: gcp
      type: network
      field: ip
      index: 0
      ipcalc: base
post_onboard_enabled: []
