# These github actions will perform linting using pre-commit.
# yamllint disable rule:line-length
---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: dev
    steps:
      - uses: actions/checkout@v3
      - name: install talisman
        run: |
          sudo curl -sLo /usr/local/bin/talisman https://github.com/thoughtworks/talisman/releases/download/v1.27.0/talisman_linux_amd64
          sudo chmod 0755 /usr/local/bin/talisman
      - uses: actions/setup-python@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - uses: pre-commit/action@v2.0.3
